services:
  budget-db:
    image: mysql:8.4
    container_name: budget-db
    environment:
      MYSQL_DATABASE: budgeting_app
      MYSQL_ROOT_PASSWORD_FILE: ./backend/secrets/mysql_root_password.txt
      MYSQL_USER_FILE: ./backend/secrets/mysql_user.txt
      MYSQL_PASSWORD_FILE: ./backend/secrets/mysql_user_password.txt
    volumes:
      - db-data:/var/lib/mysql
      - ./backend/secrets:/run/secrets:ro
    ports:
      - "3306:3306"

  spring-boot:
    build:
      context: ./backend
    container_name: spring-boot
    depends_on:
      - budget-db
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: default

volumes:
  db-data:
